### ISSUE TITLE
Building with perl

### ISSUE THREAD

**Issue by mcpdevelopment** [dendory/NodePoint#1]
Can you please upload all the modules that you used because I have tried building with perl and if is not working

**Comment by mydogz97** [comment]
Yes I had the same exact issue when I tried to build nodepoint with perl app for Windows or Linux. The modules could not be found in perl and some of the modules you cannot even find online. It would be greatly appreciated if you could include all the modules in the github repository that way people who would like to build it using the perl script can. Thanks and keep up the good work really enjoy node point

**Comment by mcpdevelopment** [comment]
It is good to know that someone else is experiencing this issue also. I was starting to think it was just me or that there was something wrong with my machine. I tried downloading all the modules listed also but as you said some could not be found. Also the ones that were found caused more errors. let's hope that dendory sees this and can provide us with the module.

**Comment by dendory** [comment]
Sorry about missing this issue. Are you trying to run the script or compile it into a binary? I run it on a pretty default Perl 5.20. Let me know the errors you get.

**Comment by mcpdevelopment** [comment]
Thanks for getting back to me when i try to build nodepoint using the nodepoint.pl file and the nodepoint.perlapp file with perl app I get an error that says that I am missing modules. It seems like the modules that you call in the nodepoint.pl file aren't included with the default perl install and a lot of the modules I cannot even find online

**Comment by dendory** [comment]
I can't help unless I see the exact errors. Yes there are additional modules, LDAP for example, I don't have a full list but you can see which ones by looking at the top of the Perl file. To install them I just do: ppm install module

**Comment by mcpdevelopment** [comment]
this is the error code I got


The specified CGI application misbehaved by not returning a complete set of HTTP headers. The headers it did return are "Array found where operator expected at Carp.pm line 502, at end of line (Do you need to predeclare Carp::longmess?) Array found where operator expected at Carp.pm line 503, at end of line (Do you need to predeclare Carp::shortmess?) Array found where operator expected at Carp.pm line 504, at end of line (Do you need to predeclare Carp::shortmess?) Array found where operator expected at Carp.pm line 505, at end of line (Do you need to predeclare Carp::longmess?) syntax error at Carp.pm line 502, near "Carp::longmess @_" syntax error at Carp.pm line 503, near "Carp::shortmess @_" syntax error at Carp.pm line 504, near "Carp::shortmess @_" syntax error at Carp.pm line 505, near "Carp::longmess @_" BEGIN failed--compilation aborted at /<D:\www\nodepoint\www\nodepoint.exe>Config/Win32.pm line 4. BEGIN failed--compilation aborted at nodepoint.pl line 11. "

**Comment by dendory** [comment]
Make sure it's loading the Config module that's provided in this package, not one you may already have installed on your system. Also, I'm assuming this is on a Windows host? There's a number of 'Linux' to change to 'Win32' in the script, or vice and versa if you run it on Linux. Is this running the Perl script or did you compile a new binary? You can run it from a command line btw so you don't have to try to debug error messages in a browser.

**Comment by mcpdevelopment** [comment]
i get this when i compile a new binary and run it via IIS and I made sure that I was running the config module you provided and that i changed all the linux to win32

**Comment by mcpdevelopment** [comment]
This is the new error message I got when I ran the Binary

The specified CGI application misbehaved by not returning a complete set of HTTP headers. The headers it did return are "Can't load 'auto/APR/APR.dll' for module APR: load_file:The specified module could not be found at /<D:\www\nodepoint\www\nodepoint.exe>DynaLoader.pm line 224. at perlapp line 831. BEGIN failed--compilation aborted at /<D:\www\nodepoint\www\nodepoint.exe>Socket.pm line 23. BEGIN failed--compilation aborted at /<D:\www\nodepoint\www\nodepoint.exe>Net/SMTP.pm line 13. BEGIN failed--compilation aborted at nodepoint.pl line 15. ".

**Comment by dendory** [comment]
Does it run as a Perl script, not compiled? There's one module that PerlApp doesn't like, something like ldap/inet6.pm (I'll check the name tomorrow) that you may need to rename.

**Comment by dendory** [comment]
I pushed a screenshot of the exact packages I have installed with versions, so you can compare and see which may be causing issues.

**Comment by mcpdevelopment** [comment]
Thanks after installing the packages that you had I was able to get the program to work. It was that some of the packages where older and some were newer than the ones you had. I really like what you created. Just some suggestions do you think you can add a field in the ticket area that allows the person creating the ticket to assign an agent to that ticket without having to go in and edit the ticket, also could you add a field for uploading images for the ticket where the new ticket field is not after when you edit the ticket. Thanks again for all your help and keep up the good work looking forward to see what else you create

**Comment by mcpdevelopment** [comment]
It seems like there are some issues when it comes to being able to access the program outside of the local host like with a domain name for some reason the program keeps blocking connections. This is while using iis manager 8 on windows server 2012 r2.

**Comment by dendory** [comment]
Do you mean for the initial configuration screen or other places? The only restriction it used to have is for initial config which should be done from local host. Other than that there is no blocking system so you'll have to show me what you mean.

**Comment by dendory** [comment]
Thanks for the suggestions, I've added most of them in 1.4.4. Projects and tickets can already be deleted by the admin only, since it can make many orphaned items (tickets, comments, linked articles) so it should be used carefully.

**Comment by mcpdevelopment** [comment]
Hi again,
Thanks for adding those features. I still cannot seem to when I am creating a new ticket there isn't a field to assign the ticket to someone. Also do you think you could make in the custom field a drop down menu that way people could select from some of the most basic issues and say if their issue wasn't there they click a button that creates a new field in the drop down so that it is added. Also is it possible that each of the fields for the custom form be a different coloum in the data base. Besides that I can't but praise this program it has saved me so much time by allowing me to keep track of all the issues in one place and I would highly recommend this to anyone. Thanks again dendory and keep up the good work.

**Comment by mcpdevelopment** [comment]
Hi again,
Thanks for adding those features. I still cannot seem to when I am creating a new ticket there isn't a field to assign the ticket to someone. Also do you think you could make in the custom field a drop down menu that way people could select from some of the most basic issues and say if their issue wasn't there they click a button that creates a new field in the drop down so that it is added. Also is it possible that each of the fields for the custom form be a different coloum in the data base. Besides that I can't but praise this program it has saved me so much time by allowing me to keep track of all the issues in one place and I would highly recommend this to anyone. Thanks again dendory and keep up the good work.

**Comment by mcpdevelopment** [comment]
Hi again,
Thanks for adding those features. I still cannot seem to when I am creating a new ticket there isn't a field to assign the ticket to someone. Also do you think you could make in the custom field a drop down menu that way people could select from some of the most basic issues and say if their issue wasn't there they click a button that creates a new field in the drop down so that it is added. Also is it possible that each of the fields for the custom form be a different coloum in the data base. Besides that I can't but praise this program it has saved me so much time by allowing me to keep track of all the issues in one place and I would highly recommend this to anyone. Thanks again dendory and keep up the good work.

**Comment by dendory** [comment]
Having a 'common issue' field type is a good idea, I would probably merge that with articles, so you can write articles about common issues and the user can select an article. For assignment, one base principle of NodePoint is a lower access level cannot assign something to someone higher, ever. Users can assign themselves to tickets, or auto assign themselves to projects, or be notified by someone who edits a ticket. At the most, I could see about adding a custom field to notify someone from a custom form.

**Comment by mcpdevelopment** [comment]
okay thanks and that would make sense and i know just from my experience using it the ability to assign for someone level 3 and above would be helpful. and yes the drop down ability in the custom forms would save a lot of time so thank you for considering that. do you think that you will also implement the separate columns for each field in the custom form because i know from a data analysis point of view it is easier to mine the data that way
