### ISSUE TITLE
hard to config on Ubuntu

### ISSUE THREAD

**Issue by L30Yu** [dendory/NodePoint#2]
Hi, I am new on all of these. when I run ./setup.sh on Ubuntu, it would not easy.
I have figured out that the apache user name is www-data, the apache2 is located at /etc/apache2, the apache config file is located at /etc/apache2/apache2.conf

But, I still can not make it work. if i open 127.0.0.1/nodepoint      , i could only see a list of files in the nodepoint folder on browser.

i appreciate you sharing this project. I really need your help.

Thank you.

**Comment by dendory** [comment]
Check the troubleshooting section in the manual. If you're seeing a list of files then it's likely you do not have AllowOverride set in your Apache config, or it's set to None. Locate it and change it to All.

**Comment by L30Yu** [comment]
hi, I still can not make it work. AllowOverride is set as All in config. still just a list of files: http://104.130.231.71/nodepoint/

**Comment by dendory** [comment]
Your symlink should point to the www subfolder, not to nodepoint. Also make sure NodePoint has write access to the files:

chown -R www-data /path/to/nodepoint

This should be done by the setup script but somehow it didn't on your system.

**Comment by L30Yu** [comment]
i tried, i think i failed.

Could you provide some other ways to finish this step? such as download the source code and use node command to start the project?

**Comment by dendory** [comment]
Node runs JavaScript applets. That has nothing to do with this.

What failed? Can you run other CGIs on your server? Did you do the symlink?

**Comment by L30Yu** [comment]
i really do not know much. do you mind login into my server and help me figure it out? my email: springyulei@gmail.com, i will reply you my server info

**Comment by dendory** [comment]
I ran it on a brand new Ubuntu system and ran into just 2 issues. The Apache restart didn't go through since Apache has a different service name on Ubuntu versus RHEL/CentOS, and CGI is apparently not enabled by default over there. I modified the setup script to take care of these particularities. Please open a new issue with specific errors if you run into more problems.
