### ISSUE TITLE
Missing database?

### ISSUE THREAD

**Issue by anthonyjr2** [dendory/NodePoint#4]
Just got started setting up NodePoint for a small group of people, but I've run into a roadblock. Do we need to create the database ourselves? When I try to run the initial configuration it asks for the db path but since nothing exists yet I can't actually create the config. I figured there would be some sort of skeleton database that the initial config would then populate with data, but the db folder in the download is empty.

Can anyone tell me what I'm doing wrong?

**Comment by dendory** [comment]
It's fine if the folder is empty, just make sure your web server has write access to the folder.

**Comment by anthonyjr2** [comment]
Wow, I can't believe it was that simple. Thanks for the quick response it configured fine now!
